# Generated by Django 5.0.2 on 2025-05-14 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('short_info', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('link', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('affiliation', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from the title.', max_length=220, unique=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='theses/')),
                ('abstract', models.TextField(blank=True, help_text='A brief summary of the thesis.')),
                ('pdf', models.FileField(blank=True, help_text='Optional PDF of the full thesis.', upload_to='theses/papers/')),
                ('link', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ThesisParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('supervisor', 'Supervisor'), ('principal_investigator', 'Principal Investigator')], max_length=30)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayfalar.person')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayfalar.thesis')),
            ],
            options={
                'unique_together': {('thesis', 'person', 'role')},
            },
        ),
        migrations.AddField(
            model_name='thesis',
            name='participants',
            field=models.ManyToManyField(related_name='theses', through='sayfalar.ThesisParticipation', to='sayfalar.person'),
        ),
    ]
