# Generated by Django 5.0.2 on 2025-02-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(choices=[('GL', 'Group Leader'), ('GS', 'Graduate Student'), ('PM', 'Previous Member')], max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='research_topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', help_text='Select whether the thesis is ongoing or completed.', max_length=10)),
                ('author', models.CharField(help_text='Name of the thesis author.', max_length=100)),
                ('start_date', models.DateField(help_text='The start date of the thesis.')),
                ('end_date', models.DateField(blank=True, help_text='The end date of the thesis (if applicable).', null=True)),
                ('description', models.TextField(blank=True, help_text='Optional additional details about the thesis.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True, help_text='Link to the thesis (if available).')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project_type', models.CharField(choices=[('research', 'Research Projects'), ('student', 'Student Projects')], default='research', help_text='Select whether this is a Research Project or a Student Project.', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('coordinators', models.ManyToManyField(blank=True, related_name='coordinated_projects', to='sayfalar.member')),
                ('researchers', models.ManyToManyField(blank=True, related_name='research_projects', to='sayfalar.member')),
                ('scholars', models.ManyToManyField(blank=True, related_name='scholar_projects', to='sayfalar.member')),
            ],
        ),
    ]
