# Generated by Django 5.0.2 on 2025-05-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
