# Generated by Django 5.0.2 on 2025-05-14 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0002_alter_thesis_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('project_type', models.CharField(choices=[('research', 'Research Project'), ('student', 'Student Project')], default='research', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('link', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('supervisor', 'Supervisor'), ('principal_investigator', 'Principal Investigator')], max_length=30)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayfalar.person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayfalar.project')),
            ],
            options={
                'unique_together': {('project', 'person', 'role')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(related_name='projects', through='sayfalar.ProjectParticipation', to='sayfalar.person'),
        ),
    ]
