# Generated by Django 5.0.2 on 2025-05-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0003_project_projectparticipation_project_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('position_type', models.CharField(choices=[('UG', 'Undergraduate'), ('GR', 'Graduate'), ('PD', 'Postdoctoral')], default='UG', max_length=2)),
                ('description', models.TextField(help_text='Main description of the position')),
                ('eligibility', models.TextField(blank=True, help_text='Who is eligible')),
                ('skills', models.TextField(blank=True, help_text='Required skills')),
                ('commitment', models.CharField(blank=True, help_text="E.g. '10–15 hrs/week' or '2–3 years'", max_length=100)),
                ('contact_email', models.EmailField(help_text='Email to apply', max_length=254)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'ordering': ['order', 'position_type', 'title'],
            },
        ),
    ]
